---
- name: Discover the EC2 instance region
  # Reversing the string is hacky but readable and efficient enough...
  shell: "ec2metadata --availability-zone | rev | cut -c 2- | rev"
  register: ec2_region

- name: Configure /tmp/awslogs.conf
#  sudo: yes
  template:
    dest: /tmp/awslogs.conf
    mode: 0600
    src: awslogs.conf.j2

- name: Download the awslogs-agent-setup.py script
#  sudo: yes
  get_url:
    dest: /tmp/awslogs-agent-setup.py
    mode: 0600
    url: https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py

- name: Install the AWS CloudWatch Logs daemon
  sudo: yes
  shell: python /tmp/awslogs-agent-setup.py -n -r {{ ec2_region.stdout }} -c /tmp/awslogs.conf

- name: Copy systemd unit file
  sudo: yes
  copy:
    src=awslogs.service
    dest=/lib/systemd/system/awslogs.service
    owner=root
    group=root
    mode=644
    backup=yes

  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: Enable the service
  shell: "systemctl enable awslogs.service"
  sudo: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'


- name: Start the service
  sudo: yes
  service: name=awslogs state=started